### ISSUE TITLE
Add serverless version to repo

### ISSUE THREAD

**Issue by slang25** [FSharpBristol/FSharp-Template-for-Aws-Lambda#1]
Serverless 1.4 adds support for C# https://github.com/serverless/serverless/pull/2863
Let's do the the same with this template 😃 I'll make a start, feel free to jump in

**Comment by lukemerrett** [comment]
@slang25 I'll look at converting this project to use serverless (I'll keep it in a sub folder for now so there are options)

**Comment by slang25** [comment]
Cool, let me put up the WIP PR for your reference too, will just be a few minutes.

**Comment by lukemerrett** [comment]
- [x] Setup [Hello Word in CSharp](https://github.com/jimmyp/serverless/blob/75f7fe78e138d6bfbe011d1cabef4b4f1538cb3e/docs/providers/aws/examples/hello-world/csharp/README.md) template
- [x] Convert to use the F# project.json and files
- [x] Add a build.cmd for us Windows lot
- [x] Add a Readme on setup instructions pointing [here](https://github.com/jimmyp/serverless/tree/75f7fe78e138d6bfbe011d1cabef4b4f1538cb3e)
- [x] Test package and deployment
- [x] Test remote invocation
- [ ] PR serverless branch

**Comment by slang25** [comment]
https://github.com/serverless/serverless/pull/3045

**Comment by lukemerrett** [comment]
Implemented in PR: https://github.com/lukemerrett/FSharp-Template-for-Aws-Lambda/pull/3
